name: ZMGDesktop Workflow CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    
      - name: Print path
        run: Write-Host $env:GITHUB_WORKSPACE
        shell: pwsh
        
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Navigate to root folder
        run: cd Software/ZMGDesktop

      - name: Restore NuGet Packages
        working-directory: Software/ZMGDesktop
        run: nuget restore
        
      - name: Restore NuGet Packagesv2
        working-directory: Software/ZMGDesktop/ZMGDesktop
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/ZMGDesktop
        
      - name: Restore NuGet Packagesv3
        working-directory: Software/ZMGDesktop/ZMG.IntegrationTests
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/ZMG.IntegrationTests
        
      - name: Restore NuGet Packagesv4
        working-directory: Software/ZMGDesktop/ZMGDesktop_Tests
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/ZMGDesktop_Tests
        
      - name: Restore NuGet Packagesv5
        working-directory: Software/ZMGDesktop/EntitiesLayer
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/EntitiesLayer
        
      - name: Restore NuGet Packagesv6
        working-directory: Software/ZMGDesktop/Email
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/Email
        
      - name: Restore NuGet Packagesv7
        working-directory: Software/ZMGDesktop/BusinessLogicLayer
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/BusinessLogicLayer
        
      - name: Restore NuGet Packagesv8
        working-directory: Software/ZMGDesktop/DataAccessLayer
        run: nuget restore packages.config -PackagesDirectory Software/ZMGDesktop/DataAccessLayer
            
      - name: Build Solution
        working-directory: Software/ZMGDesktop
        run: msbuild /p:platform="Any CPU" /p:configuration=Release ZMGDesktop.sln

      - name: Run Unit tests
      #  working-directory: Software/ZMGDesktop/ZMGDesktop_Tests
        run: dotnet test --configuration Release --filter ZMGDesktop_Tests.ZMGDesktop_Tests

      - name: Run Integration tests
        working-directory: Software/ZMGDesktop/ZMG.IntegrationTests
        run: dotnet test --configuration Release --filter ZMG.IntegrationTests.ZMGIntegrationTests

      - name: Publish applications
        run: msbuild /t:publish /p:configuration=Release /p:PublishDir=publish/ Software/ZMGDesktop/ZMGDesktop.csproj

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ZMGDesktopSetup
          path: Software/ZMGDesktop/ZMGDesktop/publish/

      - name: Install SonarLint
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"ZMGDesktop" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build and Analyze with SonarLint
        working-directory: Software/ZMGDesktop
        run: |
          msbuild /t:restore
          msbuild /t:build /t:sonarqube /p:Configuration=Release /p:Platform="Any CPU" /p:SonarQubeAnalysisConfigPath=sonar-project.properties
