name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet Packages
      working-directory: Software/ZMGDesktop
      run: dotnet restore ZMGDesktop.sln

    - name: Build Solution
      working-directory: Software/ZMGDesktop
      run: dotnet build ZMGDesktop.sln --configuration Release --no-restore

    - name: Run Unit tests
      working-directory: Software/ZMGDesktop/ZMGDesktop_Tests
      run: dotnet test --configuration Release --no-restore --filter ZMGDesktop_Tests.ZMGDesktop_Tests

    - name: Run Integration tests
      working-directory: Software/ZMGDesktop/ZMG.IntegrationTests
      run: dotnet test --configuration Release --no-restore --filter ZMG.IntegrationTests.ZMGIntegrationTests
