name: ZMGDesktop Workflow - CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Navigate to root folder
        run: cd $GITHUB_WORKSPACE
        
      - name: Restore NuGet Packages
        run: nuget restore Software/ZMGDesktop/ZMGDesktop.sln -SolutionDirectory Software/ZMGDesktop
        
      - name: Restore NuGet Packages
        working-directory: Software/ZMGDesktop/ZMGDesktop
        run: nuget restore -PackagesDirectory
    
      - name: Build Solution
        working-directory: Software/ZMGDesktop
        run: msbuild /p:platform="Any CPU" /p:configuration=Release
        
      - name: Run Unit tests
        working-directory: Software/ZMGDesktop
        run: dotnet test --configuration Release --filter ZMGDesktop_Tests.ZMGDesktop_Tests
        
      - name: Run Integration tests
        working-directory: Software/ZMGDesktop
        run: dotnet test --configuration Release --filter ZMG.IntegrationTests.ZMGIntegrationTests
      
      - name: Navigate to startup project
        run: cd ZMGDesktop
        
      - name: Publish applications
        run: msbuild /t:publish /p:configuration=Release /p:PublishDir=publish/
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ZMGDesktopSetup
          path: ZMGDesktop/publish/
      
      - name: Install SonarLint
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"ZMGDesktop" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        
      - name: Build and Analyze with SonarLint
        run: |
          msbuild /t:restore
          msbuild /t:build /t:sonarqube /p:Configuration=Release /p:Platform="Any CPU" /p:SonarQubeAnalysisConfigPath=sonar-project.properties
